language: node_js
node_js:
- '0.12'
branches:
  only:
  - source
before_install:
#- openssl aes-256-cbc -K $encrypted_49abf1879d02_key -iv $encrypted_49abf1879d02_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d

- openssl aes-256-cbc -K $encrypted_49abf1879d02_key -iv $encrypted_49abf1879d02_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d

- chmod 600 ~/.ssh/id_rsa
- cd ~/.ssh
- ll
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- cat ~/.ssh/config
- npm install -g hexo-cli
install:
- npm install
before_script:
- git config --global user.name 'zshaney'
- git config --global user.email 'zshaney@gmail.com'
script:
- hexo clean
- hexo g
- hexo d
